# Generated by Django 5.0.3 on 2024-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
